name: 🐞 問題回報
description: 回報在 Han1meViewer 中出現的問題
labels: [bug]
body:

  - type: textarea
    id: actual-behavior
    attributes:
      label: 實際行為
      description: 請簡短解釋實際發生的事
      placeholder: |
        Example:
          "我打開 Han1meViewer 發生了..."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 預期行為
      description: 請簡短解釋你應該發生的事
      placeholder: |
        Example:
          "我應該要..."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Han1meViewer version
      description: 你的**Han1meViewer**版本
      placeholder: |
        Example: "v0.14.0"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android version
      description: 你的**Android**版本
      placeholder: |
        Example: "Android 13"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      description: 你的設備型號
      placeholder: |
        Example: "Google Pixel 5"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: 其他
      placeholder: |
        其他詳細的說明
